# netlify.toml - GÜNCELLENMİŞ VERSİYON

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# API yönlendirmeleri (Proxy Kuralları)
# Bu kurallar, /api/ ile başlayan istekleri doğru sunucu fonksiyonuna gönderir.
# status = 200, bunun bir "rewrite" olduğunu, yani URL'nin değişmeden
# arka planda yönlendirme yapılacağını belirtir.

[[redirects]]
  from = "/api/tmdb/*"
  to = "/.netlify/functions/tmdb-proxy/:splat"
  status = 200

[[redirects]]
 from = "/api/gemini/*"
  to = "/.netlify/functions/gemini-proxy/:splat"
  status = 200

[[redirects]]
  from = "/api/suggest-movie"
  to = "/.netlify/functions/suggest-movie"
  status = 200

# Tek Sayfa Uygulamaları (SPA) için Geri Dönüş Kuralı
# Bu kural, yukarıdaki API kurallarıyla eşleşmeyen TÜM diğer istekleri
# ana index.html sayfanıza yönlendirir. Bu, sayfa yenilendiğinde 404 hatası
# almamanızı sağlar. Bu kuralın EN SONDA olması çok önemlidir.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200